### ISSUE TITLE
yesod

### ISSUE THREAD

**Issue by alexkazik** [naushadh/persistent#2]
Unfortunately persistent-mysql-haskell does not work as a drop-in replacement in the yesod-mysql stack template.

This is due to two problems:
1. in Application.hs myConnInfo and myPoolSize is used
2. the FromJSON instance of MySQLConf expects that the port is a string value in the json

I would appreciate a yesod-mysql-haskell template.

**Comment by naushadh** [comment]
Here's what I found:

- stack templates for `yesod-*` are auto-generated from this repo: [yesod-scaffold@mysql](https://github.com/yesodweb/yesod-scaffold/tree/mysql).
- upon inspection, the compatibility issues you pointed out could be easily addressed without having to fork a whole new template.

Proposed changes:
- [ ] Add new API `myConnInfo :: MySQLConf -> MySQLConnectInfo`
- [ ] Add new API `myPoolSize :: MySQLConf -> Int`
- [ ] Parse port as an integral value

@alexkazik: Can you confirm whether the above will address the highlighted problems and offer drop in compatibility?

**Comment by alexkazik** [comment]
When the proposed changes are made the template/code has only to be altered very little in order to work.

I guess that this is as close as possible since persistent-mysql/-haskell seems to not support InitCommand.

Here are the still required changes:

```diff
diff --git a/src/Settings.hs b/src/Settings.hs
--- a/src/Settings.hs
+++ b/src/Settings.hs
@@ -16,13 +16,12 @@ import Data.Aeson                 (Result (..), fromJSON, withObject, (.!=),
                                    (.:?))
 import Data.FileEmbed             (embedFile)
 import Data.Yaml                  (decodeEither')
-import Database.Persist.MySQL     (MySQLConf (..))
+import Database.Persist.MySQL     (MySQLConf)
 import Language.Haskell.TH.Syntax (Exp, Name, Q)
 import Network.Wai.Handler.Warp   (HostPreference)
 import Yesod.Default.Config2      (applyEnvValue, configSettingsYml)
 import Yesod.Default.Util         (WidgetFileSettings, widgetFileNoReload,
                                    widgetFileReload)
-import qualified Database.MySQL.Base as MySQL
 
 -- | Runtime settings to configure this application. These settings can be
 -- loaded from various sources: defaults, environment variables, config files,
@@ -73,7 +72,7 @@ instance FromJSON AppSettings where
                 False
 #endif
         appStaticDir              <- o .: "static-dir"
-        fromYamlAppDatabaseConf   <- o .: "database"
+        appDatabaseConf           <- o .: "database"
         appRoot                   <- o .:? "approot"
         appHost                   <- fromString <$> o .: "host"
         appPort                   <- o .: "port"
@@ -90,16 +89,6 @@ instance FromJSON AppSettings where
         appCopyright              <- o .:  "copyright"
         appAnalytics              <- o .:? "analytics"
 
-        -- This code enables MySQL's strict mode, without which MySQL will truncate data.
-        -- See https://github.com/yesodweb/persistent/wiki/Database-Configuration#strict-mode for details
-        -- If you choose to keep strict mode enabled, it's recommended that you enable it in your my.cnf file so that it's also enabled for your MySQL console sessions.
-        -- (If you enable it in your my.cnf file, you can delete this code).
-        let appDatabaseConf = fromYamlAppDatabaseConf { myConnInfo = (myConnInfo fromYamlAppDatabaseConf) {
-                MySQL.connectOptions =
-                  ( MySQL.connectOptions (myConnInfo fromYamlAppDatabaseConf)) ++ [MySQL.InitCommand "SET SESSION sql_mode = 'STRICT_ALL_TABLES';\0"]
-              }
-            }
-
         appAuthDummyLogin         <- o .:? "auth-dummy-login"      .!= dev
 
         return AppSettings {..}
```

To parse the port as integer change `read port` into `fromIntegral (port :: Word16)`.

**Comment by naushadh** [comment]
@alexkazik you're right re: `initCommand`. I'm okay with the API additions/tweaks. Feel free to open a PR if you like. Alternatively I can take it too.

**Comment by pangwa** [comment]
+1....

**Comment by alexkazik** [comment]
Here is my try. I couldn't test it with yesod since the stack yesod templates require persistent < 2.8 but the current repo requires >= 2.8.

Hope it helps though.

[patch.diff.txt](https://github.com/naushadh/persistent/files/1777590/patch.diff.txt)

**Comment by alexkazik** [comment]
Sorry for the long wait.
I finally had time to (upgrade my project to Yesod 1.6/Persist 2.8) and check it: it works fine!

Here is an updated yesod readme section which will enable utf8mb4 as suggested by https://github.com/naushadh/persistent/issues/5 and a text about the mysql strict mode.

[README.Yesod.txt](https://github.com/naushadh/persistent/files/1885740/README.Yesod.txt)

**Comment by alexkazik** [comment]
I think I found another Problem.

**Comment by alexkazik** [comment]
I totally forgot the changes on Application.hs.
Once again an updated readme, sorry for that.
[README.Yesod.txt](https://github.com/naushadh/persistent/files/1887651/README.Yesod.txt)

In case you want to make urf8mb4 globally the default or switchable I should update it again.
(There is a new utf8mb4 issue, I described in https://github.com/naushadh/persistent/issues/5.)

**Comment by alexkazik** [comment]
I've updated the readme of you fix branch: https://github.com/alexkazik/persistent/commits/fix-2

I'm also working on mysql-haskell to make it possible to select the default encoding, I'll try to add the patch here also.

**Comment by naushadh** [comment]
@alexkazik I've left out the blurb re: `utf8mb4` since as you noted in #5 the table creation is still UTF8 and it's a halfway fix. I've applied the rest of the patch.

Since you'd already verified the fix works for you, I'm going to merge https://github.com/naushadh/persistent/pull/6.

**Comment by Burtannia** [comment]
After the merge yesterday I've been trying to get things up and running. Everything builds fine but I get problems starting the yesod app. I've detailed them on StackOverflow [here](https://stackoverflow.com/questions/51200980/yesod-network-socket-connect-failed-connection-refused). I would appreciate it if you could take a look (for some reason the post is getting down voted so maybe it's really obvious and I'm just being an idiot).

**Comment by naushadh** [comment]
@Burtannia sounds like a connection issue independent of yesod/persistent/mysql-haskell -- I reckon you get the same error when you try the host to be say "google.com" (clearly a host where mysql isn't running/listening).

I'd suggest searching up the particular error code; i.e., https://stackoverflow.com/questions/40474451/cant-connect-to-database-10061

**Comment by Burtannia** [comment]
@naushadh Thanks, you're correct that it was a MySQL connection issue. After fixing that, I'm now getting the following error:

`devel.hs: ERRException (ERR {errCode = 1251, errState = "08004", errMsg = "Client does not support authentication protocol requested by server; consider upgrading MySQL client"})`

Searching it brings me to this page: https://dev.mysql.com/doc/refman/5.7/en/old-native-pluggable-authentication.html

Am I correct in thinking `mysql-haskell` is configured for old versions of MySQL? If so it should probably be updated for security.

EDIT: After checking the docs for `mysql-haskell` it seems it has been tested with MySQL 5.7 so I'm not sure what the problem is.

EDIT2: After further Googling I found [this](https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server) post, the answer of which fixed things for me.

**Comment by kebp** [comment]
With a recent mariadb (10.3.12) I can only get this to work if I also change the database port in yesod's config/settings from 5432 to 3306 which appears to be the current default port for mariadb.  Might it be helpful if the README was updated with a note to this effect?
